/* 
 * File:   main.cpp
 * Author: Richard Martin
 * Created on March 10, 2018, 8:52 PM
 * Purpose: A program that calculates the income generated by a stadium based
 * on number of tickets sold and ticket price entered.
 */
//  Gaddis_7th Edition_Ch. 3_Problem 2_This program will ask the user to enter
//  how many tickets were sold at each price point, then display the amount of 
//  income generated by the ticket sales.

#include <iostream>
using namespace std;

int main ()
{
    double classA, classB, classC, income;
    
    cout << "This program calculates the income generated by a stadium based on"
            "the number of tickets sold at the three price points."<<endl;
    cout << "How many Class A tickets were sold? ";
    cin >> classA;
    classA = 15.00 * classA;
    cout << "How many Class B tickets were sold? ";
    cin >> classB;
    classB = 12.00 * classB;
    cout << "How many Class C tickets were sold? ";
    cin >> classC;
    classC = 9.00 * classC;
    income = classA + classB + classC;
    cout << "A total of $" << income << " was generated by ticket sales."<<endl;
    return 0;
    
}

